YAPP-Github/20th-Android-Team-1-FE

- buildSrc/src/main/java/Versions.kt
- resolved #4 
<br>
- Kotlin version : 1.6.10 -> 1.6.20
- Compose version : 1.1.1 -> 1.2.0-alpha08
<br>
<br>
> [ISSUE-004] Kotlin&Compose version 수정

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- resolved #34 
<br>
- PR 템플릿 Check List 중 제목 규칙이 잘못된 부분을 수정합니다
- ISSUE 템플릿을 추가합니다(수정하는 김에 간단하게 추가해 보았습니당)
<br>
<br>
> [ISSUE-34] 템플릿 추가 및 수정

- presentation/src/main/java/com/yapp/growth/ui/sample/SampleViewModel.kt
<br>
- 머지 중 발생한 충돌 처리
- `SampleViewModel` 에서 파라미터로 주었던 `useCase` 제거
<br>
<br>
> [FIX] 머지 중 발생한 충돌 처리

- app/src/main/res/values-v31/themes.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/themes.xml
- presentation/src/main/java/com/yapp/growth/presentation/theme/Color.kt
- presentation/src/main/java/com/yapp/growth/presentation/theme/Theme.kt
- presentation/src/main/java/com/yapp/growth/presentation/theme/Type.kt
- resolved #46 
<br>
- 변경된 컬러 시스템 적용
- 변경된 폰트 시스템 적용
- 앱 이름 변경
<br>
<br>
> [ISSUE-46] 변경된 컬러 시스템 및 폰트 시스템 적용

- data/src/main/java/com/yapp/growth/data/internal/response/PromisingTimeTableResponseImpl.kt
- data/src/main/java/com/yapp/growth/data/mapper/TimeTableResponseToModelMapper.kt
- data/src/main/java/com/yapp/growth/data/repository/ConfirmPlanRepositoryImpl.kt
- data/src/main/java/com/yapp/growth/data/response/PromisingTimeTableResponse.kt
- data/src/main/java/com/yapp/growth/data/source/ConfirmPlanDataSource.kt
- data/src/main/java/com/yapp/growth/data/source/ConfirmPlanDataSourceImpl.kt
- domain/src/main/java/com/yapp/growth/domain/entity/Entity.kt
- domain/src/main/java/com/yapp/growth/domain/entity/TimeTable.kt
- domain/src/main/java/com/yapp/growth/domain/entity/TimeTableDate.kt
- domain/src/main/java/com/yapp/growth/domain/entity/TimeTableUnit.kt
- domain/src/main/java/com/yapp/growth/domain/repository/ConfirmPlanRepository.kt
- domain/src/main/java/com/yapp/growth/domain/usecase/GetRespondUsersUseCase.kt
- presentation/src/main/java/com/yapp/growth/presentation/component/PlanzIndicator.kt
- presentation/src/main/java/com/yapp/growth/presentation/component/PlanzTimeTable.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/createPlan/CreatePlanScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/manage/confirm/ConfirmPlanContract.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/manage/confirm/ConfirmPlanScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/manage/confirm/ConfirmPlanViewModel.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/manage/respond/RespondPlanContract.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/manage/respond/RespondPlanScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/manage/respond/RespondPlanViewModel.kt
- presentation/src/main/java/com/yapp/growth/presentation/util/Extends.kt
- presentation/src/main/res/values/strings.xml
- domain 레이어의 엔티티를 정리했습니다.
- User 엔티티를 따로 공통으로 사용하게끔 분리했습니다.
- APi 네이밍 변경이 있어서 대응
<br>
<br>
> [Refactor] domain 엔티티 정리 & Api 네이밍 변경에 따른 수정 및 코드정리

- data/src/main/java/com/yapp/growth/data/api/GrowthApi.kt
- data/src/main/java/com/yapp/growth/data/di/DataSourceModule.kt
- data/src/main/java/com/yapp/growth/data/di/RepositoryModule.kt
- data/src/main/java/com/yapp/growth/data/internal/source/DetailDataSourceImpl.kt
- data/src/main/java/com/yapp/growth/data/repository/DetailRepositoryImpl.kt
- data/src/main/java/com/yapp/growth/data/source/DetailDataSource.kt
- domain/src/main/java/com/yapp/growth/domain/repository/DetailRepository.kt
- domain/src/main/java/com/yapp/growth/domain/usecase/GetFixedPlanUseCase.kt
- presentation/src/main/java/com/yapp/growth/presentation/component/PlanzCalendar.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/PlanzScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/detail/DetailPlanScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/detail/DetailPlanViewModel.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/CalendarDecorator.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeContract.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeViewModel.kt
- presentation/src/main/res/values/strings.xml
- resolved #106
<br>
- 약속 상세 화면 API 연동
- 캘린더 관련 일부 로직 변경
<br>
| Screen Shot | 
| ----------- | 
|  ![Screenshot_1658518977](https://user-images.githubusercontent.com/85336456/180519905-e6bdd243-eacf-4920-bc37-c0e2704f40c5.png)           |      
<br>
> [ISSUE-106] 약속 상세 화면 API 연동

- presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeContract.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeViewModel.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/myPage/MyPageContract.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/myPage/MyPageScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/myPage/MyPageViewModel.kt
- resolved #121 
<br>
- 홈, 내 정보 화면에 유저 API를 연동
- 이제 김정호가 아니라 각자의 이름으로 표시됩니다..
> [ISSUE-121] 홈, 내 정보 화면 유저 API 연동

- presentation/src/main/java/com/yapp/growth/presentation/ui/login/LoginActivity.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/login/LoginContract.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/login/LoginScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/login/LoginViewModel.kt
- resolved #118 
<br>
- 비로그인 둘러보기 기능을 추가했습니다.
<br>
| Screen Shot |
| ----------- |
|![image](https://user-images.githubusercontent.com/33443660/180657122-ddde3430-c1f3-4d2d-bb09-fa167e6a489d.png)|
<br>
> [ISSUE-118] 비로그인 둘러보기 기능 추가

- presentation/src/main/java/com/yapp/growth/presentation/component/PlanzDialog.kt
- presentation/src/main/java/com/yapp/growth/presentation/component/PlanzError.kt
- presentation/src/main/java/com/yapp/growth/presentation/component/PlanzLoading.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/myPage/MyPageScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/myPage/MyPageViewModel.kt
- presentation/src/main/res/values/strings.xml
- resolved #125 
<br>
- 로딩 공통 컴포넌트 추가
- 에러 공통 컴포넌트 추가
- 다이얼로그 공통 컴포넌트 추가
- 홈 화면에 공통 컴포넌트 적용
<br>
| ![Screenshot_1658808091](https://user-images.githubusercontent.com/85336456/180920335-d5770e6e-2d63-4f24-b628-1d56ebc3294c.png)            |       ![Screenshot_1658808053](https://user-images.githubusercontent.com/85336456/180920345-c67f15ba-d27d-42fc-9ac8-08ef5f37c75e.png)      |
| ![Screenshot_1658807984](https://user-images.githubusercontent.com/85336456/180920347-95605905-d0ca-4812-99fe-8cd6eb408208.png) |
<br>
> [ISSUE-125] 로딩, 에러, 다이얼로그 공통 컴포넌트 추가

- .github/workflows/android.yml
- resolved #{issue_number}
<br>
- 작업 범위를 작성해 주세요
<br>
<br>
> 파이어베이스 로컬프로퍼티 android.yml 추가

- presentation/src/main/java/com/yapp/growth/presentation/ui/main/myPage/MyPageViewModel.kt
- resolved #146 
<br>
- 탈퇴하기 다이얼로그 버튼 동작 정상화
> [ISSUE-146] 탈퇴하기 다이얼로그 버튼 동작 정상화

- buildSrc/src/main/java/Configs.kt
- presentation/src/main/java/com/yapp/growth/presentation/component/PlanzAppBar.kt
- presentation/src/main/java/com/yapp/growth/presentation/component/PlanzIconAndTextAppBar.kt
- presentation/src/main/java/com/yapp/growth/presentation/component/PlanzTimeTable.kt
- presentation/src/main/java/com/yapp/growth/presentation/component/PlanzTwoIconAppBar.kt
- presentation/src/main/java/com/yapp/growth/presentation/firebase/DynamicLink.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/createPlan/CreatePlanScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/createPlan/share/ShareScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/createPlan/share/ShareViewModel.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/PlanzScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/confirm/FixPlanScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/monitor/MonitorPlanViewModel.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/respond/result/RespondPlanCompleteScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/respond/result/RespondPlanRejectScreen.kt
- presentation/src/main/res/values/strings.xml
- 다이나믹 링크 썸네일 추가
- 약속 거절 화면 오류 수정
- 약속 응답, 확정 현황 화면 패딩 수정
- release r1.0.3 테스트
<br>
- 작업 범위를 작성해 주세요
<br>
> release 1.0.3 버전배포 및 오류수정

- presentation/src/main/java/com/yapp/growth/presentation/ui/createPlan/title/TitleScreen.kt
- resolved #176
<br>
- 약속 생성 STEP 2 타이틀 변경
<br>
| <img width="510" alt="스크린샷 2022-08-02 오후 9 29 35" src="https://user-images.githubusercontent.com/42907876/182374900-cc32480f-7b94-485e-ab3f-3f46b16cd38e.png"> |             |
<br>
> [ISSUE-176] 약속 생성 STEP 2 타이틀 변경

- presentation/src/main/java/com/yapp/growth/presentation/component/PlanzError.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/createPlan/CreatePlanContract.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/createPlan/CreatePlanViewModel.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/createPlan/timerange/TimeRangeContract.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/createPlan/timerange/TimeRangeScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/createPlan/timerange/TimeRangeViewModel.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/createPlan/timetable/CreateTimeTableScreen.kt
- presentation/src/main/res/values/strings.xml
- resolved #142 
<br>
- 약속 생성 STEP4 Alert Dialog 추가
<br>
| <img width="510" alt="스크린샷 2022-08-02 오후 11 07 00" src="https://user-images.githubusercontent.com/42907876/182394883-63019a06-d3c0-4f47-aba3-425c936654a2.png"> |             |
<br>
> [ISSUE-142] 약속 생성 STEP4 Alert Dialog 추가

- presentation/src/main/java/com/yapp/growth/presentation/ui/createPlan/theme/ThemeScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/createPlan/title/TitleScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/manage/ManageScreen.kt
- resolved #178
<br>
- 약속 생성 STEP1 로딩/에러 처리
- 약속 생성 STEP2 로딩/에러 처리
- 약속 관리 로딩/에러 처리
<br>
<br>
> [ISSUE-178] 약속 생성 및 약속 관리 로딩/에러 처리

- presentation/src/main/java/com/yapp/growth/presentation/component/PlanzBottomSheetScaffold.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/fix/FixPlanViewModel.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/monitor/MonitorPlanViewModel.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/respond/RespondPlanViewModel.kt
- resolved #{issue_number}
<br>
- 작업 범위를 작성해 주세요
<br>
<br>
> 응답자 바텀시트 포맷 수정

- presentation/src/main/java/com/yapp/growth/presentation/component/PlanzSnackBar.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/createPlan/timerange/TimeRangeScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/createPlan/timetable/CreateTimeTableScreen.kt
- presentation/src/main/res/values/strings.xml
- resolved #190
- resolved #193 
<br>
- 스낵바 위치 조정
- 약속 생성 STEP 3, 4 타이틀 텍스트 변경
- Alert Dialog String Resource 이름 변경
<br>
<br>
> [ISSUE-190 & 193] 스낵바 위치 조정, 약속 생성 STEP 3, 4 타이틀 텍스트 변경

- presentation/src/main/java/com/yapp/growth/presentation/component/PlanzTextField.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/createPlan/title/TitleScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/myPage/nickname/ModifyNickNameScreen.kt
- resolved #187 
<br>
- PlanzTextField 키보드 옵션 및 액션 추가
- 약속 생성 키보드 액션 추가
- 닉네임 변경 키보드 액션 추가
<br>
<br>
> [ISSUE-187] 키보드 액션 추가

- presentation/src/main/java/com/yapp/growth/presentation/ui/main/PlanzScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/detail/DetailPlanViewModel.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeContract.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
- presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeViewModel.kt
- presentation/src/main/java/com/yapp/growth/presentation/util/Extends.kt
- presentation/src/main/res/values/strings.xml
- resolved #209 
- resolved #208 
- resolved #207 
- resolved #206 
- 홈 화면 바텀시트 애니메이션이 들쭉날쭉한 현상 해결
- 약속 상세보기에서 장소 정보가 나타나지 않는 현상 해결
- 약속 상세보기에서 30분 단위로 확정시 정각으로 조회되는 현상 해결
- 홈 화면 캘린더 이전 달, 이후 달까지 API 연동 함께 하도록 수정
- 홈 오류 발생 시 스낵바 이벤트 발생하도록 설정
> [QA] 2차 수정

- buildSrc/src/main/java/Configs.kt
- resolved #{issue_number}
<br>
- 작업 범위를 작성해 주세요
<br>
<br>
> [release] r1.1.1 업데이트
